### ISSUE TITLE
Consider showing the latest emitted value from an observable in the explorer

### ISSUE THREAD

**Issue by mgechev** [rangle/angular-devtools#562]
Observable objects in the side panel (inputs, state, etc) aren't that interesting to look at. Would be more useful to be able to see the last emitted value for example, so more of a first-class support.

**Comment by DmitryEfimenko** [comment]
why was this closed? Was it implemented?

I think the request was not only for outputs of directives. These days a lot of developers write components using rxjs almost exclusively (no imperative style coding). For these cases it's hard to use the angular-devtools to inspect the state of the component since the state is implemented via Subjects.

**Comment by magnusbakken** [comment]
Didn't Augury have this feature? I haven't used Augury in a long time, but I seem to recall being able to see the "current" value of observables, which was quite useful.

What I would mostly use this for is to see the last emitted values of the observables on my services. I'm not sure where directives come into the picture.
